# Generated by Django 4.0.5 on 2022-07-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
    ]
